# References
#https://medium.com/@nitinbhardwaj6/selenium-grid-with-docker-c8ecb0d8404
version: "3"
services:

  hub:
    image: selenium/hub
    container_name: Hub
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000

 

  chrome-original:
    image: selenium/node-chrome-debug
    container_name: web-automation_chrome-original
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "49154:5900"
    links:
      - hub

    chrome-snap:
      image: selenium/node-chrome-debug
      container_name: web-automation_chrome-snap
      depends_on:
        - hub
      environment:
        HUB_PORT_4444_TCP_ADDR: hub
        HUB_PORT_4444_TCP_PORT: 4444
        NODE_MAX_SESSION: 4
        NODE_MAX_INSTANCES: 4
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "49153:5900"
      links:
        - hub

  #firefox-debug: 
  #  image: selenium/node-firefox-debug
  #  container_name: web-automation_firefox-debug
  #  depends_on:
  #    - hub
  #  environment:
  #    HUB_PORT_4444_TCP_ADDR: hub
  #   HUB_PORT_4444_TCP_PORT: 4444
  #    NODE_MAX_SESSION: 4
  #    NODE_MAX_INSTANCES: 4
  #  volumes:
  #    - /dev/shm:/dev/shm
  #  ports:
  #    - "49153:5900"
  #  links:
  #   - hub

  #chrome:
   # image: selenium/node-chrome
    #container_name: web-automation_chrome
    #depends_on:
     # - hub
    #environment:
     # HUB_PORT_4444_TCP_ADDR: hub
      #HUB_PORT_4444_TCP_PORT: 4444
      #NODE_MAX_SESSION: 4
      #NODE_MAX_INSTANCES: 4
    #volumes:
     # - /dev/shm:/dev/shm
    #ports:
     # - "9001:5900"
    #links:
     # - hub

  #firefox:
   # image: selenium/node-firefox
    #container_name: web-automation_firefox
    #depends_on:
     # - hub
    #environment:
     # HUB_PORT_4444_TCP_ADDR: hub
      #HUB_PORT_4444_TCP_PORT: 4444
      #NODE_MAX_SESSION: 4
      #NODE_MAX_INSTANCES: 4
    #volumes:
     # - /dev/shm:/dev/shm
    #ports:
     # - "9002:5900"
    #links:
     # - hub
    